name: test
on: workflow_dispatch
jobs:
  first_workflow:
    runs-on: ubuntu-latest
    steps:
      - name : Sample
        run : echo "Hello"
      - name : Checkout
        uses : actions/checkout@v3
      - name : install node
        uses : actions/setup-node@v3
        with:
          node-version: 16
      - name : mock installed
        run : echo "Node Installed"
