name: testWorkFlow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Setup
        run : echo "Set up"
      - name : Checkout
        uses : actions/checkout@v3
      - name : install node
        uses : actions/setup-node@v3
        with:
          node-version: 16
      - name : mock installed
        run : echo "Node Installed"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name : Setup
        run : echo "Sample deploy setup"
      - name : Process
        run : echo "Processing"
      - name : Post deploy
        run : echo "Deployed successfully"
